create table tab_city (id bigint not null auto_increment, col_name varchar(255), col_state_id bigint not null, primary key (id)) engine=InnoDB;
create table tab_cuisine (id bigint not null auto_increment, col_desc varchar(255), col_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_group (id bigint not null auto_increment, col_name varchar(255), primary key (id)) engine=InnoDB;
create table tab_group_permission (col_group_id bigint not null, col_permission_id bigint not null) engine=InnoDB;
create table tab_method_payment (id bigint not null auto_increment, col_description varchar(255), primary key (id)) engine=InnoDB;
create table tab_permission (id bigint not null auto_increment, col_description varchar(255), primary key (id)) engine=InnoDB;
create table tab_product (id bigint not null auto_increment, col_active bit, col_description varchar(255), col_name varchar(255), col_price decimal(19,2), col_restaurant_id bigint, primary key (id)) engine=InnoDB;
create table tab_restaurant (id bigint not null auto_increment, col_address_cep varchar(255), col_address_complement varchar(255), col_address_district varchar(255), col_address_logradouro varchar(255), col_address_number varchar(255), col_date_register datetime not null, col_date_update datetime not null, col_name varchar(255) not null, col_tax_shipping decimal(19,2) not null, col_address_city_id bigint, col_cuisine_id bigint not null, primary key (id)) engine=InnoDB;
create table tab_restaurant_methods_payment (col_restaurant_id bigint not null, col_method_payment_id bigint not null) engine=InnoDB;
create table tab_state (id bigint not null auto_increment, col_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tab_user (id bigint not null auto_increment, col_date_registration datetime, col_name varchar(255), primary key (id)) engine=InnoDB;
create table tab_user_group (col_user_id bigint not null, col_group_id bigint not null) engine=InnoDB;
alter table tab_city add constraint FKgn4jjl0ucf3kxuqfo2wgqjskr foreign key (col_state_id) references tab_state (id);
alter table tab_group_permission add constraint FKh27mex3y4ih78vl08kb0vmwri foreign key (col_permission_id) references tab_permission (id);
alter table tab_group_permission add constraint FK7nk5u4sj48wun39ub41he4ji6 foreign key (col_group_id) references tab_group (id);
alter table tab_product add constraint FKg0ym6ossdpn04bdg90mx83xtm foreign key (col_restaurant_id) references tab_restaurant (id);
alter table tab_restaurant add constraint FK7sc5qhht9xniiios4yepetpen foreign key (col_address_city_id) references tab_city (id);
alter table tab_restaurant add constraint FK77vfipoagk7w9ys1qj4hlip4u foreign key (col_cuisine_id) references tab_cuisine (id);
alter table tab_restaurant_methods_payment add constraint FK14si6godj5cmd03g70xpye2ci foreign key (col_method_payment_id) references tab_method_payment (id);
alter table tab_restaurant_methods_payment add constraint FKmhrswstphy2hak3is50trquc6 foreign key (col_restaurant_id) references tab_restaurant (id);
alter table tab_user_group add constraint FK1xrkosixw6r85rftargsvl6i0 foreign key (col_group_id) references tab_group (id);
alter table tab_user_group add constraint FK2m9yq5m81i8o3a0xiobkrgln8 foreign key (col_user_id) references tab_user (id);
insert into tab_cuisine (col_name) values ('Thai');
insert into tab_cuisine (col_name) values ('Indian');
insert into tab_cuisine (col_name) values ('Brazilian');
insert into tab_cuisine (col_name) values ('Japan');
insert into tab_state (col_name) values ('Ceará');
insert into tab_state (col_name) values ('Bahia BA');
insert into tab_city (col_name, col_state_id) values ('Fortaleza', 1);
insert into tab_city (col_name, col_state_id) values ('Salvador', 2);
insert into tab_city (col_name, col_state_id) values ('Crateús', 1);
insert into tab_restaurant (col_name, col_tax_shipping, col_cuisine_id, col_date_register, col_date_Update) values ('Thai Gourmet', 10, 1, current_timestamp, current_timestamp);
insert into tab_restaurant (col_name, col_tax_shipping, col_cuisine_id, col_date_register, col_date_Update) values ('Indi ganesha', 7.30, 2, current_timestamp, current_timestamp);
insert into tab_restaurant (col_name, col_tax_shipping, col_cuisine_id, col_date_register, col_date_Update, col_address_cep, col_address_logradouro, col_address_number, col_address_complement, col_address_district, col_address_city_id) values ('Tradição Mineira', 0.0, 3, current_timestamp, current_timestamp, '99999999', 'Vasco da Gama', '4003', 'Loja 212', 'ADEOTA', 1);
insert into tab_product (col_name, col_description, col_price, col_active, col_restaurant_id) values ('Pad Thai', 'Prato de macarrão com arroz frito', 55.00, true, 1);
insert into tab_method_payment (col_description) values ('Pix');
insert into tab_method_payment (col_description) values ('Credit card');
insert into tab_restaurant_methods_payment (col_restaurant_id,col_method_payment_id) values (1, 1), (1, 2),(2, 1),(2, 2),(3, 1);
insert into tab_permission (col_description) values ('Adm');
insert into tab_permission (col_description) values ('Client');
